apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wg5m2yzcj-dotnet-basic 
  janus-idp.io/tekton: wg5m2yzcj-dotnet-basic
  backstage.io/kubernetes-id: wg5m2yzcj-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wg5m2yzcj-dotnet-basic
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml